[general]
port = 8090
debug = 1
mock = 1
logLevel = 0
runMode = 1

[redis]
address = "localhost"
port = 6379

[database]
host = "47.103.123.140"
port = 10086
user = "usersApi"
pwd = "skl@654321"
name = "users"